const express = require('express');
│   │   const connectDB = require('./config/db');
│   │   const authRoutes = require('./routes/authRoutes');
│   │   const productRoutes = require('./routes/productRoutes');
│   │   const orderRoutes = require('./routes/orderRoutes');
│   │   require('dotenv').config();
│   │   connectDB();
│   │   const app = express();
│   │   app.use(express.json());
│   │   app.use('/api/auth', authRoutes);
│   │   app.use('/api/products', productRoutes);
│   │   app.use('/api/orders', orderRoutes);
│   │   app.listen(5000, () => console.log('Server running on port 5000'));